import type { Metadata } from "next";
import { customFont } from "./fonts";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import { Footer } from "@/components/layouts/Footer";


export const metadata: Metadata = {
  title: "Balenciaga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={customFont.className}>
        <Navbar />
      <main>{children}</main>
      <Footer />
        </body>
    </html>
  );
}
