import type { Metadata } from "next";
import { customFont } from "./fonts";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import { Footer } from "@/components/layouts/Footer";
import Provider from "@/utils/provider";
import AuthInitializer from "@/components/AuthInitializer";
export const metadata: Metadata = {
  title: "Balenciaga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={customFont.className}>
        <Provider>
          <AuthInitializer />
        <Navbar />
          <main>{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
